### ISSUE TITLE
what do username and pasword have to be passed in base64 encoded strings?

### ISSUE THREAD

**Issue by Marak** [Marak/node_mailer#14]
seems like a bad api choice. should have it pass in passwords as plaintext here, and have the module itself base64 encode it.

**Comment by saschagehlich** [comment]
Sure, just take this library here https://github.com/saschagehlich/node-mailer/blob/master/vendor/base64.js and simply do base64.encode(pwd);

**Comment by Marak** [comment]
:-D

```
      /*
       * base64.js: An extremely simple implementation of base64 encoding / decoding using node.js Buffers
       *
       * (C) 2010, Nodejitsu Inc.
       *
       */

      var base64 = exports;

      base64.encode = function (unencoded) {
        return new Buffer(unencoded || '').toString('base64');
      };

      base64.decode = function (encoded) {
        return new Buffer(encoded || '', 'base64').toString('utf8');
      };
```

**Comment by Marak** [comment]
neat trick ya?

**Comment by saschagehlich** [comment]
Well sure, that works as well. Don't know why I used that library but I had a reason I guess.

**Comment by Marak** [comment]
Node's old API didn't have built in base64 support, so a few of the older libs still have a base64.js vendored.

**Comment by Marak** [comment]
lets close this and file it under v0.5.0

https://github.com/Marak/node_mailer/issues/#issue/17
