### ISSUE TITLE
Receiving error "could not connect"

### ISSUE THREAD

**Issue by zdzolton** [Marak/node_mailer#16]
Hi,

I'm trying to send an email via SendGrid, but I keep getting a {message:"could not connect"} error.

Here's my test program:

```
var inspect, opts, puts, sys;
sys = require('sys');
puts = sys.puts, inspect = sys.inspect;
opts = {
  host: "smtp.sendgrid.net",
  port: "25",
  domain: "smtp.sendgrid.net",
  authentication: "login",
  username: new Buffer("My SendGrid Username").toString("base64"),
  password: new Buffer("My SendGrid Password").toString("base64"),
  to: "My Email Address",
  from: "test@example.com",
  subject: "Node.js Test Email",
  body: "Do it, dawg!"
};
puts("send options: " + (inspect(opts)));
require('mailer').send(opts, function() {
  return puts(inspect(arguments));
});
```

Any ideas of what I can try to fix this? FYI, I'm running node v0.2.6 and mailer v0.4.4.

Thanks!

**Comment by Marak** [comment]
Is it possible to test using the 0.3.x brand of node? I haven't tested using the 0.2.x brand in a while, but it should work.

I'll try to test later today and see what I can do. It would be awesome if we could get some proper test coverage for this library.

**Comment by zdzolton** [comment]
Well, so far I've stayed away from 0.3.x, since I was under the impression that node does even/odd minor version numbers to indicate stable/unstable. Is that the case?

My real problem is that—aside from the snippet I posted above—I've got a fairly large 0.2.6-tested application to which I'm trying to add email capabilities. I've been under the impression that 0.3.x has API changes, so I haven't been eager to try porting it yet...

Anyways, sorry for the rant and thank you for taking a look into this!

**Comment by Marak** [comment]
There have been a bunch of updates,do you want to try again with the new version? There are also a few other node mailers kicking around aside from this library.

**Comment by zdzolton** [comment]
I'm happy to report that I've received an email from the test script, by upgrading to the new mailer v0.4.5 package.

Thanks!

**Comment by Marak** [comment]
sweeeeeeet! let me know if you have any additional issues.
