### ISSUE TITLE
Version 0.5.0 Feature Requests

### ISSUE THREAD

**Issue by Marak** [Marak/node_mailer#17]
Okay, there have been a lot of tickets opened regarding better error handling for connections and for sending emails. I'm closing all of these tickets and forwarding them here. 

In v0.5.0 of node_mailer we will address some fundmental API changes that will alleviate a lot of the issues being experienced. We will also be introducing some new features that will make the experience of sending mail a bit more pleasant.

**Comment by Marak** [comment]
- username and password can be passed in as plaintext
- spool mode
- waits for server HELO before sending
- make sure all commands are sent in Uppercase

**Comment by arlolra** [comment]
- address formatting (ie. "Arlo &lt;arlolra@gmail.com>" doesn't seem to work for me )
- baked in base64 ( https://gist.github.com/718390 )

**Comment by Marak** [comment]
I think the only outstanding issue we have now is the baked in base64 support for username and passwords.

@bmeck Does that sound right?

**Comment by bmeck** [comment]
Sounds right, we can move to just be using plaintext tonight. its a tiny fix.

On Wed, May 18, 2011 at 4:52 PM, Marak
reply@reply.github.com
wrote:
