### ISSUE TITLE
node_mailer sucks

### ISSUE THREAD

**Issue by Marak** [Marak/node_mailer#20]
Are any of the other mailer libraries good enough to warrant depreciating this library, or should we push forward?

**Comment by malkomalko** [comment]
I like https://github.com/andris9/Nodemailer

Not a lot of followers yet but it is really feature packed and put together well.

**Comment by Marak** [comment]
It seems good, but I don't have much time to test throughly. I'll keep supporting this library until there is a clear better solution.

**Comment by izuzak** [comment]
Just noticed emailjs -- https://github.com/eleith/emailjs

**Comment by dresende** [comment]
Another one, https://github.com/dresende/node-smtp

**Comment by Marak** [comment]
Does anyone know which has the most solid SMTP implementation? I think the best course of action for the node_mailer project at this point would be to vendor one of the other libs for its SMTP library and then build a slightly friendly API on top that replicates the current node_mailer API.

**Comment by mikeal** [comment]
SMTP alone isn't hard at all, but there are a ton of extensions people use that you'll want to implement.

**Comment by dresende** [comment]
Could you tell me some of them? I only see auth extensions as essential..

**Comment by Marak** [comment]
Okay, it's been decided that this library will.....LIVE.

Backup troops are incoming with a new version in the next couple of weeks. The current version is operational, but I'd be wary of using it for sending any large lists or really important messages.

**Comment by Marak** [comment]
New version of the library has been completed thanks to @bmeck and @andris9. There is a blog post coming soon explaining the changes. Until then, the code is all published and live...get at it!

**Comment by balor** [comment]
I was testing several libraries and Nodemailer (https://github.com/andris9/Nodemailer) works for me.

**Comment by Marak** [comment]
@balor We are using NodeMailer as a dep now, did you read the whole thread? I'm closing this now to avoid further confusion.
