### ISSUE TITLE
Implement better SMTP support

### ISSUE THREAD

**Issue by Marak** [Marak/node_mailer#23]
I'm not 100% confident in our current implementation of SMTP. We should review the STMP logic and compare it against:

https://github.com/andris9/Nodemailer/blob/master/lib/smtp.js
and
https://github.com/dresende/node-smtp/blob/master/lib/smtp.js

We should then determine the best one and implement. The licenses for both of those libraries allow us to re-use the code, so if we decide to use one of the other implementations, we should maintain upstream commits ( if applicable ).

**Comment by bmeck** [comment]
Cross issue : https://github.com/bmeck/node_mailer/issues/1

**Comment by Marak** [comment]
New SMTP lib implemented with version 5, closed.
