### ISSUE TITLE
Hack back in templates

### ISSUE THREAD

**Issue by Marak** [Marak/node_mailer#26]
We removed templates when we did a the refactor to version 5. We need to add these back in ASAP.

**Comment by bmeck** [comment]
I can do that tonight if it has that priority.

On Wed, May 18, 2011 at 1:36 PM, Marak
reply@reply.github.com
wrote:

**Comment by Marak** [comment]
Should be completed with: https://github.com/Marak/node_mailer/commit/fb8c11e2e023593c8a987671533d2f35b5068cb9

@bmeck - Feel free to review my implementation for correctness, but I wouldn't spend too much time. I'm pretty sure my new template cache implementation will work the same as the old, but also negate any potential "dog pile" effect on doing file reads. ( Should now ensure that only ONE file read is ever done per template...)

**Comment by wbw** [comment]
Hi, I'm looking towards this or NodeMailer for email support. I'm new to Node (& GitHub for that matter) but upon looking at your templating code noticed that your not yet cached version assigns the template result to the HTML part of the message and your cached version assigns it to the body of the message. Is this deliberate?

**Comment by Marak** [comment]
This should already be implemented. I have no idea what you are asking about. 

Open up a new issue with a line number and a more clear question.
