### ISSUE TITLE
Reply-To

### ISSUE THREAD

**Issue by zdzolton** [Marak/node_mailer#27]
It would be nice if this library presented a way to accept a reply-to header value.

**Comment by bmeck** [comment]
on it

On Fri, May 27, 2011 at 8:13 AM, zdzolton
reply@reply.github.com
wrote:

**Comment by zdzolton** [comment]
Much appreciated!

I'll watch the commits here, so that next time perhaps I can hit you with a
Pull Request instead of a Feature Request... LOL

**Comment by bmeck** [comment]
pushed out in 0.6.1, use the reply_to option, example now in demo.js

**Comment by zdzolton** [comment]
Do you think this would apply cleanly to the 0.3 line? I'm still stuck on
Node 0.2.6 and can't upgrade to the later versions of this library.

Thank you!

**Comment by bmeck** [comment]
im not sure. I dont think so. it would really depend if NodeMailer
supports 0.2.6

On Fri, May 27, 2011 at 9:01 AM, zdzolton
reply@reply.github.com
wrote:

> Do you think this would apply cleanly to the 0.3 line? I'm still stuck on
> Node 0.2.6 and can't upgrade to the later versions of this library.
> 
> Thank you!
> 
> On Fri, May 27, 2011 at 8:52 AM, bmeck <

**Comment by Marak** [comment]
@zdzolton - You REALLY should upgrade to 0.4.8. Is there a specific reason you are still using the old version? It's really not advised, at all.

**Comment by zdzolton** [comment]
You're right, I should upgrade to the latest Node.js version.

My dev team has been "just about" to release our product, built using 0.2.6,
for the past couple months. I've just been reluctant to cause any
disruptions from upgrading.

Anyways, thanks for implementing that featurehopefully I can take advantage
of it soon!

**Comment by Marak** [comment]
@zdzolton If you have a production system that needs to be migrated from 0.2.x to 0.4.x, I'd be willing to assist if you run into any issues. I can't guarantee availability, but I'll definitely be able to provide pointers should you run into any specific issues.

Obviously, I am unsure about the complexities of your application so maybe the migration will be harder then I think.
