### ISSUE TITLE
Add support for secure connections via the STARTTLS command

### ISSUE THREAD

**Issue by izuzak** [Marak/node_mailer#3]
Basically, extend the options configuration dictionary to support some sort of "secure" parameter which is either set to "false" or to a crypto credentials object which can then automatically be  used if the server supports TLS. This gist is a good starting point: https://gist.github.com/312809. Obviously, things have changed a bit, but the core of the functionality is the same. 

Having a working GMail demo would be great for node_mailer. :)

**Comment by Marak** [comment]
experimental ssl support has now been implemented.
