### ISSUE TITLE
attachments or custom content type

### ISSUE THREAD

**Issue by bentomas** [Marak/node_mailer#4]
It would be cool if you could add attachments, but that seems like a lot of work.  What about making it so you can specify a custom content type and if it is set then node_mailer doesn't add all that stuff in itself, so I could format the body myself but let this library handle all the details of sending the emails...

**Comment by Marak** [comment]
I'll make content-type an optional parameter you can pass in, that should be a decent start.

**Comment by Marak** [comment]
Content-Type fixed with bentomas patch, thank you!

https://github.com/Marak/node_mailer/commit/defd5603e54167f0006ee41c7405cb03548384db

**Comment by piscis** [comment]
is there any chance getting the content-type patch in to npm release soon? I need it  to set charset encoding

**Comment by Marak** [comment]
i'll publish new version today

**Comment by Marak** [comment]
published to npm 0.4.2

**Comment by piscis** [comment]
Hi Marak thx again I´m upgrading to 0.4.2 now
