### ISSUE TITLE
Which node.js hosting solutions support smtp?

### ISSUE THREAD

**Issue by balupton** [Marak/node_mailer#42]
Hey guys, while not directly related to node_mailer I just can't find any information on which node.js hosting solutions actually support smtp - and figured this would be the best place to ask.

Turns our that the joyent no.de smart machines don't! And it's only available in their premium solutions - which don't function in the same way as their no.de offering - so bugger.

So... any ideas?

**Comment by Marak** [comment]
I'm slowly getting the feeling using STMP protocol is fucked in general.

Sendgrid.com offers a web api for sending emails, you can access this over http.

MailChimp provides kick ass features for doing email blasts, no smtp required.

We are currently using a combination of both. 

Hope that helps...

**Comment by balupton** [comment]
Using node_mailer with sendgrid still times out on joyent's no.de hosting...

**Comment by balupton** [comment]
this was the config I used:

```
from: 'eventlyapp@gmail.com'
host: 'smtp.sendgrid.net'
port: '587'
domain: 'yourdomain.com'
authentication: 'login'
username: 'balupton'
```

works fine locally

here is the exact error:

```
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ETIMEDOUT, Connection timed out',
  errno: 145,
  code: 'ETIMEDOUT',
  syscall: 'connect' } undefined
```

**Comment by Marak** [comment]
Joyent may restrict outgoing STMP connections from their machines.

Either way, do yourself a favor and use sendgrid's HTTP API.

**Comment by balupton** [comment]
In all honesty, I thought I was ;-) Does node_mailer provide an interface for that?

**Comment by Marak** [comment]
No. node_mailer is for SMTP, not sendgrid's proprietary HTTP API.
