### ISSUE TITLE
Allow using sendmail binary directly

### ISSUE THREAD

**Issue by jamonation** [Marak/node_mailer#67]
Many systems do not run an SMTP server and instead deliver mail locally or relay to a remote SMTP server using /usr/sbin/sendmail binary.

 It would be very useful in many environments to send mail directly using /usr/sbin/sendmail without requiring TCP overhead of localhost connections, and to maintain a secure server environment without any mail daemons running.

Examples of such programs include sSMTP, msmtp, Postfix with /usr/sbin/sendmail binary replacement, or even sendmail configured only as a local relay agent.

How difficult would it be to implement a sendmail method in addition to SMTP?

**Comment by andris9** [comment]
node_mailer uses [Nodemailer](https://github.com/andris9/Nodemailer) as its [sending engine](http://blog.nodejitsu.com/node-mailer-redux), which supports sendmail, so if you'd figure out how to access the Nodemailer object behind the node_mailer module you could probably be able to switch it to use sendmail instead.

**Comment by jamonation** [comment]
Funny I just discovered how nodemailer works in the background and am experimenting now. Thanks!
