### ISSUE TITLE
auth problems

### ISSUE THREAD

**Issue by daralthus** [Marak/node_mailer#7]
Hi there,
I tried things out and they work in telnet, but I keep unrecognized command errors when I try to send the username and the password with stream.write(), no matter in what form.. (base64, buffer, etc.)
Do you have any idea what can be wrong?

This is the response:

```
data: 220 ns1.mydomain.com Microsoft ESMTP MAIL Service, Version: 5.0.2195.7381   ready at  Thu, 9 Dec 2010 17:46:48 -0500

data: 250 ns1.mydomain.com Hello [184.106.136.245]

data: 334 VXNlcm5hbWU6
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
250 2.1.0 info@domain.com....Sender OK
550 5.7.1 Unable to relay for strandesverfurdo@gmail.com
554 5.5.2 No valid recipients
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
500 5.3.3 Unrecognized command
250 2.0.0 Resetting
221 2.0.0 ns1.mydomain.com Service closing transmission channel
```

Thx

**Comment by Marak** [comment]
Can you post a gist of the code you are running?

**Comment by daralthus** [comment]
Well it is the basic example with a remote hostname, and I added a data listener to node_mailer to see the response.. 
Then I just tried if it maybe some encoding problem around the username/password as it doesn't want to recognize them. So I tried stream.write(new Buffer("pass", 'base64'), base64); and stuff like that in the mailer source. (of course after trying it out with a simple base64 encoded string in the main app)
I would point you to the server but it is not mine so I'm not allowed to.
Anyway everything what node_mailer does, works with telnet.

**Comment by Marak** [comment]
I'll try running the code again here and see what happens.

Which version of node are you using?

**Comment by daralthus** [comment]
its 0.3.0-pre, I may update it later. thx

**Comment by Marak** [comment]
So I think that has to do with the fact you are connecting to an ESMTP server?

Is it possible to try using regular SMTP?

**Comment by Marak** [comment]
closing issue for now, i think this is related to ESMTP versus SMTP.
