### ISSUE TITLE
Unsupported Option, need MAIL command etc.

### ISSUE THREAD

**Issue by saschagehlich** [Marak/node_mailer#8]
Hey,

I'm getting the following response from the server when I try to send a mail via node_mailer:

235 2.7.0 Authentication successful
555 5.5.4 Unsupported option: sascha@gehlich.us
503 5.5.1 Error: need MAIL command
503 5.5.1 Error: need RCPT command
221 2.7.0 Error: I can break rules, too. Goodbye.

So it looks like my mailserver does not understand the commands node_mailer is sending?

**Comment by Marak** [comment]
So if I capitalize MAIL and RCPT, this should be fixed ya?
